routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;
use App\Http\Controllers\FrontController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->group(function () {
    Route::group(['middleware' => ['auth', 'role:moderator'], 'as' => 'admin.'], function () {

        Route::redirect('/', '/admin/dashboard', 301);
        Route::get('dashboard', [Admin\AdminController::class, 'index'])->name('index');
        Route::get('logs', [Admin\AdminController::class, 'logs'])->name('logs.index');
        
        Route::get('translations', function() { return view('admin.translations-index'); })->name('translations.index');
        
        Route::resource('langs', Admin\LanguageController::class);
        
        Route::get('pages/{page}/fill', [Admin\PageController::class, 'fill'])->name('pages.fill');
        Route::post('pages/{page}/fill', [Admin\PageController::class, 'fillSave'])->name('pages.fill.save');
        Route::resource('pages', Admin\PageController::class);
        
        Route::resource('testimonials', Admin\TestimonialController::class);

        Route::resource('counters', Admin\CounterController::class);
        Route::resource('timelines', Admin\TimelineController::class);

        Route::resource('jobs', Admin\JobController::class);

    });
});
$lang = 'bg';
Route::redirect('/',$lang);
Route::redirect('/login', "$lang/login");
Route::redirect('/register', "$lang/register");
Route::prefix('{language?}')->group(function () {
    Route::get('/', [FrontController::class, 'indexPage'])->name('index');

    Route::get('/patient-support-program', [FrontController::class, 'pspPage'])->name('inner-page');
    Route::get('/homecare', [FrontController::class, 'homeCare'])->name('homecare');
    Route::get('/covid-19', [FrontController::class, 'covidPage'])->name('covid-19');
    Route::get('/post-covid', [FrontController::class, 'postCovidPage'])->name('post-covid');
    Route::get('/cardiology', [FrontController::class, 'cardiologyPage'])->name('cardiology');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/contact', function () {
        return view('pages.contact');
    })->name('contact');

    Route::get('/company', [FrontController::class, 'companyPage'])->name('company');

    Auth::routes();
    
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    Route::get('/jobs', [FrontController::class, 'jobsIndex'])->name('jobs.index');
    Route::get('/jobs/{job}', [FrontController::class, 'jobsShow'])->name('jobs.show');
    
    Route::get('/{slug}', [FrontController::class, 'show'])->name('page.show');
    
});

resources/views/admin/page/fill.blade.php
<x-admin :page=$page_settings>
    <x-form.form :action="$action" :method="$method" :upload="true">

        <div class="w-100">
            <ul class="nav nav-tabs">
                @foreach (langs() as $i => $lang)
                <li class="nav-item">
                    <a class="nav-link border-left-0 @if($i == 0) active @endif" id="form-locale-{{ $lang->locale }}"
                        data-toggle="tab" href="#form_{{ $lang->locale }}" role="tab">{{ $lang->name }}</a>
                </li>
                @endforeach
            </ul>
            <div class="tab-content" id="forms">
                @foreach (langs() as $lang)
                <div class="tab-pane fade @if($loop->first) show active @endif" id="form_{{ $lang->locale }}"
                    role="tabpanel">
                    @foreach ($page->settings as $setting)
                    @php
                    $section = $page->setting($setting);
                    @endphp
                    @if($section['content'] == 'group')
                    <div class="border my-3">
                        <fieldset>
                            <legend class="ml-3">{{ $section['label'] }}</legend>
                    @endif
                    @if($section['content'] == 'endgroup')
                        </fieldset>
                    </div>
                    @endif
                    
                    
                    @if($section['content'] == 'input' && $section['type'] !== 'file')
                    <x-form.input name="data[{{ $lang->id }}][{{ $section['key'] }}]" :label="$section['label']"
                        :type="$section['type']" value="{{ (isset($data) && isset($data[$lang->id]) && key_exists($section['key'], $data[$lang->id]))
                            ? $data[$lang->id][$section['key']] : '' }}" />
                    @endif


                    @if($section['content'] == 'input' && $section['type'] == 'file')
                    <div class="card col-12 col-sm-4">
                        @if(isset($data) && isset($data[$lang->id]) && isset($data[$lang->id][$section['key']]) && is_image( $data[$lang->id][$section['key']]))
                        <img src="{{ (isset($data) && isset($data[$lang->id]) && key_exists($section['key'], $data[$lang->id]))
                        ? getPageUrl($data[$lang->id][$section['key']]) : '' }}">
                        @endif
                        @if(isset($data) && isset($data[$lang->id]) && isset($data[$lang->id][$section['key']]) )
                            <input type="hidden" name="data[{{ $lang->id }}][{{ $section['key'] }}]" value="{{ $data[$lang->id][$section['key']] }}">
                        @endif
                        <x-form.upload name="data[{{ $lang->id }}][{{ $section['key'] }}]" :label="$section['label']" />
                    </div>
                    @endif


                    @if($section['content'] == 'textarea')
                    <x-form.textarea name="data[{{ $lang->id }}][{{ $section['key'] }}]" :label="$section['label']"
                        :type="$section['type']">{{ (isset($data) && isset($data[$lang->id]) && key_exists($section['key'], $data[$lang->id]))
                        ? $data[$lang->id][$section['key']] : '' }}</x-form.textarea>
                    @endif


                    @if($section['content'] == 'html')
                    <x-form.html name="data[{{ $lang->id }}][{{ $section['key'] }}]" :label="$section['label']"
                        :type="$section['type']">{{ (isset($data) && isset($data[$lang->id]) && key_exists($section['key'], $data[$lang->id]))
                        ? $data[$lang->id][$section['key']] : '' }}</x-form.html>
                    @endif

                    @endforeach
                </div>
                @endforeach
            </div>

        </div>

    </x-form.form>
</x-admin>

resources/views/admin/page/form.blade.php
<x-admin :page=$page_settings>
    <x-form.form :action="$action" :method="$method" :upload="true">
        <x-form.input name="slug" label="Slug" required size=6
            value="{{ old('slug', isset($page) ? $page->slug : '') }}" />
        <x-form.input name="name" label="Име" required size=6
            value="{{ old('name', isset($page) ? $page->name : '') }}" />

        <x-form.textarea name="settings" label="Настройки" placeholder="key=type;label" style="min-height: 150px"
        >{{ old('settings', isset($page) ? $page->settings() : '') }}</x-form.textarea>
        <x-form.group>
            <ul>
            <li><b>#group=text</b> Ако трябва да се обединяват няколко елемента в една секция</li>
            <li><b>#endgroup</b> Затваряне на групата</li>
            <li><b>key=type;label</b> по един на ред</li>
            <li><b>key</b> - уникално име, с което се асоциират данните.</li>
            <li><b>type</b> - вида на полето.
                <ul>
                    <li>всички видове <b>input-[type]</b> (пример: <b>input-text</b>; <b>input-email</b>)</li>
                    <li><b>textarea</b></li>
                    <li><b>html</b></li>
                </ul>
            </li>
            <li><b>label</b> - Какво да пише на полето.</li>
            </ul>
        </x-form.group>
    </x-form.form>
</x-admin>

resources/views/admin/page/index.blade.php
<x-admin :page="$page">
    <x-table :columns="['Име', 'Slug', 'Действия']">
        @foreach($pages as $page)
        <tr>
            <td>{{ $page->name }}</td>
            <td>{{ $page->slug }}</td>
            <td>
                @can('admin')
                <a href="{{ route('admin.pages.edit', $page->id) }}" class="btn btn-primary"><i class="la la-edit"></i> Настройки</a>
                @endcan
                <a href="{{ route('admin.pages.fill', $page->id) }}" class="btn btn-primary"><i class="la la-edit"></i> Попълни</a>
            </td>
        </tr>
        @endforeach
    </x-table>
    <x-paginate :paginate=$pages />
</x-admin>