routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;
use App\Http\Controllers\FrontController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->group(function () {
    Route::group(['middleware' => ['auth', 'role:moderator'], 'as' => 'admin.'], function () {

        Route::redirect('/', '/admin/dashboard', 301);
        Route::get('dashboard', [Admin\AdminController::class, 'index'])->name('index');
        Route::get('logs', [Admin\AdminController::class, 'logs'])->name('logs.index');
        
        Route::get('translations', function() { return view('admin.translations-index'); })->name('translations.index');
        
        Route::resource('langs', Admin\LanguageController::class);
        
        Route::get('pages/{page}/fill', [Admin\PageController::class, 'fill'])->name('pages.fill');
        Route::post('pages/{page}/fill', [Admin\PageController::class, 'fillSave'])->name('pages.fill.save');
        Route::resource('pages', Admin\PageController::class);
        
        Route::resource('testimonials', Admin\TestimonialController::class);

        Route::resource('counters', Admin\CounterController::class);
        Route::resource('timelines', Admin\TimelineController::class);

        Route::resource('jobs', Admin\JobController::class);

    });
});
$lang = 'bg';
Route::redirect('/',$lang);
Route::redirect('/login', "$lang/login");
Route::redirect('/register', "$lang/register");
Route::prefix('{language?}')->group(function () {
    Route::get('/', [FrontController::class, 'indexPage'])->name('index');

    Route::get('/patient-support-program', [FrontController::class, 'pspPage'])->name('inner-page');
    Route::get('/homecare', [FrontController::class, 'homeCare'])->name('homecare');
    Route::get('/covid-19', [FrontController::class, 'covidPage'])->name('covid-19');
    Route::get('/post-covid', [FrontController::class, 'postCovidPage'])->name('post-covid');
    Route::get('/cardiology', [FrontController::class, 'cardiologyPage'])->name('cardiology');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/contact', function () {
        return view('pages.contact');
    })->name('contact');

    Route::get('/company', [FrontController::class, 'companyPage'])->name('company');

    Auth::routes();
    
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    Route::get('/jobs', [FrontController::class, 'jobsIndex'])->name('jobs.index');
    Route::get('/jobs/{job}', [FrontController::class, 'jobsShow'])->name('jobs.show');
    
    Route::get('/{slug}', [FrontController::class, 'show'])->name('page.show');
    
});

resources/views/admin/home.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h2 class="pageheader-title">Начало</h2>
                <p class="pageheader-text">SUIS Content Managment System</p>
                <!-- <div class="page-breadcrumb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Tables</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Data Tables</li>
                        </ol>
                    </nav>
                </div> -->
            </div>
        </div>
    </div>
@endsection

resources/views/admin/index.blade.php
<x-admin title="Dashboard">
    <div class="jumbotron mb-2">

        <h1 class="display-3">Care By SAT Health</h1>
        <p class="lead">
        </p>
    </div>
</x-admin>

resources/views/admin/log-index.blade.php
<x-admin :page="$page">
    <div class="table-responsive">
        <table class="table bg-white">
            <tr>
                <th>Resource</th>
                <th>Resource id</th>
                <th>Action</th>
                <th>User</th>
                <th>Date</th>
                <th>Message</th>
            </tr>
            @foreach($logs as $log)
            <tr>
                <td>
                    <a href="{{ route('admin.logs.index', ['type'=> $log->model_type]) }}">{{ $log->model_type }}</a>
                </td>
                <td>
                    <a
                        href="{{ route('admin.logs.index', ['type'=> $log->model_type, 'id'=> $log->model_id]) }}">{{ $log->model_id }}</a>
                </td>
                <td>{{ $log->method }}</td>
                <td>
                    @if($log->user)
                    <a href="{{ route('admin.logs.index', ['user' => $log->user_id]) }}">{{ $log->user->email }}</a>
                    @endif
                </td>
                <td>{{ $log->created_at }}</td>
                <td>
                    <pre><?php
                            $message = @unserialize($log->message);
                            if ($message) {
                                var_dump($message);
                            } else {
                                echo $log->message;
                            }
                        ?></pre>
                </td>
            </tr>
            @endforeach
        </table>
    </div>
    <div class="d-flex justify-content-center">
        {!! $logs->appends(request()->except('page'))->links() !!}
    </div>
</x-admin>

resources/views/admin/translations-index.blade.php
<x-admin :page="['page_title' => 'Преводи']">
    <iframe src="{{ url('admin/translations-manager') }}" style="width: 100%; height: 100vh "></iframe>
</x-admin>